version: '3.8'

services:
  clickhouse:
    container_name: clickhouse_db2022
    image: bitnami/clickhouse:22.3.15
    environment:
      CLICKHOUSE_ADMIN_USER: clickhouse
      CLICKHOUSE_ADMIN_PASSWORD: clickhouse
    ports:
      - "53765:8123"
