FROM bitnami/postgresql:14.5.0

ARG POSTGRES_DB

USER root
RUN apt-get update \
    && apt-get install -y postgresql-common gnupg \
    && echo -ne '\n' | sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh \
    && apt-get -y install postgresql-14-cron \
    && cp /usr/lib/postgresql/14/lib/pg_cron.so /opt/bitnami/postgresql/lib \
    && cp /usr/share/postgresql/14/extension/pg_cron* /opt/bitnami/postgresql/share/extension \
    && chmod +x /opt/bitnami/postgresql/lib/pg_cron.so

USER 1001
RUN echo "cron.database_name = '$POSTGRES_DB'" >> /opt/bitnami/postgresql/conf/conf.d/extended.conf
RUN echo "cron.use_background_workers = on" >> /opt/bitnami/postgresql/conf/conf.d/extended.conf

RUN echo "listen_addresses = '*'" >> /opt/bitnami/postgresql/conf/conf.d/extended.conf
RUN echo "max_replication_slots = 10" >> /opt/bitnami/postgresql/conf/conf.d/extended.conf
RUN echo "wal_level = logical" >> /opt/bitnami/postgresql/conf/conf.d/extended.conf
