version: "3.8"
services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:14.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    user: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 30
    restart: unless-stopped
  flyway:
    image: flyway/flyway:9.3.1
    command: -url=jdbc:postgresql://host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flask:
    container_name: ${APP_NAME}-flask
    build: .
    command: >
      sh -c "python3 -m flask run --host=0.0.0.0"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    environment:
      FLASK_RUN_PORT: ${APP_PORT}
      POSTGRES_HOST: host.docker.internal
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
